package com.e.bidding.user_service.service;

import com.e.bidding.user_service.repo.UserProfileRepo;
import com.e.bidding.user_service.utils.PDFGenerator;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.extern.slf4j.Slf4j;
import org.apache.kafka.common.protocol.types.Field;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.FileSystemResource;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import java.io.File;

@Slf4j
@Service
public class MailService {
    @Autowired
    UserProfileRepo userProfileRepo;
    @Autowired
    PDFGenerator pdfGenerator;
    private final JavaMailSender mailSender;
    private final String senderMail="minutemate111@gmail.com";

    public MailService(JavaMailSender mailSender){
        this.mailSender=mailSender;
    }


    public void sendOutBidMail(String userName,String itemDetails,double newBid,double userBid) throws MessagingException {
        String toEmail=userProfileRepo.findByUsername(userName).getEmail();

        MimeMessage message = mailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message , true);
        helper.setFrom(senderMail);
        helper.setTo(toEmail);
        helper.setSubject("Your bid has been outbid!");
        String htmlBody = "<!DOCTYPE html>\n" +
                "<html>\n" +
                "<body style='font-family: Arial, sans-serif; margin:0; padding:0;'>\n" +
                "  <table width='100%' cellpadding='20'><tr><td>\n" +
                "    <table align='center' width='600' style='background-color: #c9deff; padding:10px ;border-radius: 10px;'>\n" +
                "      <!-- Logo -->\n" +
                "      <tr>\n" +
                "        <td style='text-align:center; padding:20px;'>\n" +
                "          <img src='https://res.cloudinary.com/dbleqzcp4/image/upload/v1757704542/Add_a_heading_jxtt2l.png' width='120' alt='Logo'/>\n" +
                "        </td>\n" +
                "      </tr>\n" +
                "      <!-- Heading -->\n" +
                "      <tr>\n" +
                "        <td style='text-align:center; padding:10px;'>\n" +
                "          <h2 style='color:#7d0202;'>Outbid Notification</h2>\n" +
                "        </td>\n" +
                "      </tr>\n" +
                "      <!-- Main body text -->\n" +
                "      <tr>\n" +
                "        <td style='padding:20px; background-color:#012257; color:#ffffff; font-size:16px; border-radius: 10px; line-height:1.5;'>\n" +
                "          Dear Bidder,<br/><br/>\n" +
                "          Your bid on the item: <strong>" + itemDetails + "</strong> has been outbid by <strong>LKR " + newBid + "</strong>.<br/>\n" +
                "          Your previous bid: <strong>LKR " + userBid + "</strong>.<br/><br/>\n" +
                "          <p style='text-align:center; margin:30px 0; color:#ffffff'>Please check the item and place a new bid if you wish.\n</p>" +
                "          <p style='text-align:center; margin:30px 0;'>\n" +
                "            <a href='#' style='background-color:#FFD700; color:#012257; padding:12px 25px; text-decoration:none; border-radius:5px; font-weight:bold;'>View Item</a>\n" +
                "          </p>\n" +
                "          <p style='font-size:14px; color:#e0e0e0; text-align:center;'>\n" +
                "            This email is automatically generated by the Sri Lankan Customs e-Bidding Service. Please do not reply.\n" +
                "          </p>\n" +
                "        </td>\n" +
                "      </tr>\n" +
                "      <!-- Footer -->\n" +
                "      <tr>\n" +
                "        <td style='text-align:center; padding:10px; font-size:12px; color:#012257;'>\n" +
                "          © 2025 Sri Lankan Customs e-Bidding Service\n" +
                "        </td>\n" +
                "      </tr>\n" +
                "    </table>\n" +
                "  </td></tr></table>\n" +
                "</body>\n" +
                "</html>";

        helper.setText(htmlBody, true); // true = HTML


        mailSender.send(message);
        System.out.println("Outbid email sent to " + toEmail);

    }

    public void sendWinnerNotification(String userName,
                                       String name,
                                       Integer itemId,
                                       String itemName,
                                       String itemDescription,String claimDate,Integer amount,String location,Integer winningPlace) throws Exception {

        String toEmail=userProfileRepo.findByUsername(userName).getEmail();

        File pdf = pdfGenerator.generateOfficialLetter(name, itemId, itemName, itemDescription,claimDate,amount,location,winningPlace);

        MimeMessage message = mailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message, true);
        helper.setTo(toEmail);
        helper.setSubject("Notification of Winning Item – Sri Lankan Customs E-Bidding System");
        helper.setText(
                "Dear " + name + ",<br><br>" +
                "Congratulations! You have been awarded the item <strong>" + itemName + "</strong> through the Sri Lanka Customs E-Bidding System. " +
                "Please find attached your official award letter detailing the item and claiming instructions.<br><br>" +
                "Best regards,<br><b>Sri Lanka Customs </b>",
                true
        );
        helper.addAttachment("Customs_Official_Letter.pdf", new FileSystemResource(pdf));
        mailSender.send(message);
        log.info("Mail sent to : {}",toEmail);
    }


}
