spring.application.name=bidding-service

spring.datasource.url=jdbc:postgresql://localhost:5432/student
spring.datasource.username=postgres
spring.datasource.password=himesh
server.port=8081
jwt.secret=ofLwtTpM9ce46J1Xq6cgzKvaCiOeWOyq5LULKumA7Ik=