spring.application.name=bidding-service

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/freepdb1
spring.datasource.username=bidding
spring.datasource.password=password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8081
jwt.secret=ofLwtTpM9ce46J1Xq6cgzKvaCiOeWOyq5LULKumA7Ik=

#kafka producer
spring.kafka.producer.bootstrap-servers: localhost:9092
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.retries: 20
spring.kafka.producer.acks: all
spring.kafka.producer.retry-backoff-ms: 60000