spring.application.name=authentication-service

spring.security.user.name=himesh
spring.security.user.password=himesh

spring.datasource.url=jdbc:postgresql://localhost:5432/student
spring.datasource.username=postgres
spring.datasource.password=himesh
jwt.secret=ofLwtTpM9ce46J1Xq6cgzKvaCiOeWOyq5LULKumA7Ik=

logging.level.org.springframework.security=DEBUG