spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/user_service_db
spring.datasource.username=postgres
spring.datasource.password=himesh

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

stripe.secret.key=sk_test_51SJ8x8HqZtjJD6uK2o2tCjpMUeycMweL31CiSwTvcyAuvVOVn7cXmLBz09ghv6XeRyhuYn0NG1WNOqIZOHEQwYpj0055qgF4TV
stripe.public.key=pk_test_51SJ8x8HqZtjJD6uKJqHP6zLPnFYfK89FPoIeTz75LXQOxkHiTo78JtpNNCQqbHWuk75toh6KquAeEVC68dOxYDmM0046j493vO

spring.kafka.consumer.bootstrap-servers: localhost:9092

#consumer
spring.kafka.consumer.grop-id: user_profile
spring.kafka.consumer.auto-offset-rest: earliest
spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer:org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#producer
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.retries: 20
spring.kafka.producer.acks: all
spring.kafka.producer.retry-backoff-ms: 60000

server.port=8083
jwt.secret=ofLwtTpM9ce46J1Xq6cgzKvaCiOeWOyq5LULKumA7Ik=

#Mail service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minutemate111@gmail.com
spring.mail.password=armc ujio hxyw okry
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#item service url
item.service.url=http://localhost:8082/is/v1