spring.application.name=item-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/item
spring.datasource.username=postgres
spring.datasource.password=himesh

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.web.resources.static-locations=file:///D:/EBidingImages/

#consumer
spring.kafka.consumer.grop-id: item
spring.kafka.consumer.auto-offset-rest: earliest
spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer:org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
